### ISSUE TITLE
Prework Submission

### ISSUE THREAD

**Issue by domanhtien2011** [domanhtien2011/blogCodeSchool#1]
Hello my Code School, here is my prework. I know that there is still a video walkthrough and my image that I need to finish. However, I will try to add it tonight. If you have any feedback, please let me know. I am looking forward to join this amazing course. Thank you very much.

/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, domanhtien2011!

:tired_face: Unfortunately **there are some problems** with your submission:
- I couldn't find a walkthrough GIF referenced from your `README.md`. Please use [RecordIt](http://recordit.co) or [LICEcap](http://www.cockos.com/licecap/) to record an animated GIF of your submission going through the required stories, and include it in your `README.md`.

**Comment by domanhtien2011** [comment]
Hi Code School, I have just updated my walkthrough.gif file to my application. Please check it out. I did not use LiceCap or Recordit because they are for Windows and Mac. Therefore, I switched to Byzanz which is an alternative. My file is pretty large. So, it is going to take a while. Please be patient, and I am sorry for the convenient. The only thing I need to add now is the picture of myself, and I will add it tomorrow morning(I am pretty tired now :(). Please let me know your feedback. Thank you for your time.
/cc @coderschoolreview

**Comment by hoksilato** [comment]
Hi @domanhtien2011 

Thanks for your submitting. Great work :100:.

In summary, your submission is excellent. Everything is excellent :100:. Impressive UI. I believe your submission is one of the best (except the walkthrough gif, it made my laptop freeze :sob:, i'm just joking :D). 

There are some minor suggestions for improving, but forget them for now :clap::clap::clap: 

Let us know if you have any questions.

/cc @coderschoolreview @harley

**Comment by domanhtien2011** [comment]
Thank you Code School very much. Actually, I am trying to improving some of its functionality and UI now, and got your message. ^^

So, does it mean that I get accepted into the program?

**Comment by hoksilato** [comment]
We will send you an official email about that :dancer:

**Comment by domanhtien2011** [comment]
Thank you very much. Have a good night. And is it cool if I add some new features or UI and let you know here or I just need to push them to my github?

**Comment by hoksilato** [comment]
Have a good night. Yes, please let me know when you add some new features. Thanks :dancer: 

Actually, I starred your repo :+1:
